import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '../../components/Header';
import Footer from '../../components/Footer';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='max-w-5xl mx-auto'>
        <header className='flex justify-between items-center h-20 max-w-5xl'>
          <Link href='/'>my blog</Link>
          <div>give me money</div>
        </header>
        {children}
        <Footer />
      </body>
    </html>
  );
}
